### ISSUE TITLE
Gemini stablecoin prices

### ISSUE THREAD

**Issue by Zburatorul** [jbms/finance-dl#71]
As pointed out in #69, v1/ticker returns an error if a stablecoin is passed. Deal with this permanently.

**Comment by nlydv** [comment]
I don't think this is relevant for *all* stablecoins, just `GUSD`. When I ran it with my changes from #69 I didn't encounter any other errors even though other stablecoin symbols were part of my tx history.

Since `GUSD` is Gemini's native stablecoin, they don't float its exchange rate, so on Gemini `GUSD` is always a 1:1 conversion to `USD`. For other stablecoins, they do float but are held stable algorithmically and by the wider market, so there are actual small variations in its value.

So the ticker API still returns as expected for other stablecoins.

`DAI` https://api.gemini.com/v2/ticker/daiusd
```json
{"symbol":"DAIUSD","open":"0.99953","high":"0.99995","low":"0.95003","close":"0.99993","changes":["0.99995","0.99994","0.99985","0.99984","0.99975","0.99963","0.99974","0.99974","0.99976","0.99976","0.99971","0.9997","0.99973","0.99945","0.99966","0.99945","0.99945","0.99973","0.99966","0.99973","0.99971","0.99944","0.9995","0.99957"],"bid":"0.99994","ask":"0.99995"}
```

`GUSD` https://api.gemini.com/v2/ticker/gusdusd
```json
{"result":"error","reason":"InvalidSymbol","message":"Received unsupported symbol 'GUSDUSD'"}
```

There may be other weird edge cases though so I could be wrong.

**Comment by Zburatorul** [comment]
I see. Thanks for completing the picture for me.
I'll go ahead and merge your PR.

**Comment by nlydv** [comment]
Sure, no problem.
